### ISSUE TITLE
Wrong setting of POA, but it still finish without error

### ISSUE THREAD

**Issue by baozg** [pangenome/pggb#320]
Hi,

I wrong set `-P` with an empty variable and it was passed with `-O`. The command was `-P $POA -O 0.001`, but the `$POA` is en empty variable. It could finish without any errors. What does this take into the pggb? Is still using the asm5?

```yaml
smoothxg:
  version:            v0.7.0-18-g4ff4cf2
  skip-normalization: false
  n-haps:             61
  path-jump-max:      0
  edge-jump-max:      0
  poa-length-target:  700,900,1100
  poa-params:         -O
  poa_padding:        0.001
  run_abpoa:          false
  run_global_poa:     false
  pad-max-depth:      100
  write-maf:          false
  consensus-spec:     false
  consensus-prefix:   Consensus_
  block-id-min:       .9000
  block-ratio-min:    0

```
